#!/bin/bash
# newproject - 新專案快速啟動腳本
# 自動建立 git repo、CLAUDE.md、openspec、alias

set -e

# 顏色定義
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== 新專案啟動 ===${NC}"
echo ""

# ========== Phase 1: 互動收集資訊 ==========

# 專案名稱
read -p "專案名稱 (kebab-case): " PROJECT_NAME
if [[ -z "$PROJECT_NAME" ]]; then
    echo "錯誤: 專案名稱不能為空"
    exit 1
fi

# 驗證 kebab-case
if [[ ! "$PROJECT_NAME" =~ ^[a-z][a-z0-9-]*$ ]]; then
    echo "錯誤: 專案名稱必須是 kebab-case (小寫字母、數字、連字號)"
    exit 1
fi

# 專案目錄
read -p "專案目錄 [~/code_side/]: " PROJECT_DIR
PROJECT_DIR="${PROJECT_DIR:-$HOME/code_side}"
PROJECT_DIR="${PROJECT_DIR/#\~/$HOME}"  # 展開 ~

# 專案描述
read -p "專案描述 (一句話): " PROJECT_DESC
PROJECT_DESC="${PROJECT_DESC:-一個新專案}"

# 完整路徑
FULL_PATH="$PROJECT_DIR/$PROJECT_NAME"

echo ""
echo -e "${YELLOW}確認資訊:${NC}"
echo "  專案名稱: $PROJECT_NAME"
echo "  完整路徑: $FULL_PATH"
echo "  專案描述: $PROJECT_DESC"
echo ""
read -p "確認建立? [Y/n]: " CONFIRM
CONFIRM="${CONFIRM:-Y}"
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "已取消"
    exit 0
fi

# ========== Phase 2: 自動化建立 ==========

echo ""
echo -e "${BLUE}建立專案...${NC}"

# 建立目錄
if [[ -d "$FULL_PATH" ]]; then
    echo "錯誤: 目錄已存在 $FULL_PATH"
    exit 1
fi
mkdir -p "$FULL_PATH"
cd "$FULL_PATH"
echo -e "${GREEN}✓${NC} 建立目錄: $FULL_PATH"

# git init
git init -q
echo -e "${GREEN}✓${NC} git init"

# 建立 CLAUDE.md (with SNAPSHOT markers for repo-snapshot.sh)
cat > CLAUDE.md << EOF
# Project: $PROJECT_NAME

$PROJECT_DESC

## 專案結構
<!-- 專案建立後補充 -->

## 技術棧
<!-- 決定後補充 -->

## 上下文文件
- \`context/ARCHITECTURE.md\` - 系統架構和資料流
- \`context/DECISIONS.md\` - 設計決策記錄 (ADR)
- \`context/LEARNINGS.md\` - 經驗累積，避免重複犯錯

## 編碼規範
- TypeScript strict mode（若使用）
- 函數式風格，避免 class
- 錯誤處理：永遠 catch async 錯誤
- 命名：kebab-case 檔名，camelCase 變數
- useEffect 必須有 cleanup（timer, subscription）

## 常見錯誤紀錄
<!-- Claude 犯錯後，更新 context/LEARNINGS.md -->

<!-- SNAPSHOT:START -->
## Repo Snapshot
<!-- auto-generated by scripts/repo-snapshot.sh -->
<!-- SNAPSHOT:END -->
EOF
echo -e "${GREEN}✓${NC} 建立 CLAUDE.md"

# 建立 .gitignore
cat > .gitignore << 'EOF'
# Dependencies
node_modules/
vendor/
__pycache__/
*.pyc
.venv/
venv/

# Build
dist/
build/
*.egg-info/

# IDE
.idea/
.vscode/
*.swp
*.swo
.DS_Store

# Environment
.env
.env.local
.env.*.local
*.local

# Logs
*.log
npm-debug.log*

# Cache
.cache/
.parcel-cache/
.next/
.nuxt/

# Test
coverage/
.nyc_output/

# OS
Thumbs.db
EOF
echo -e "${GREEN}✓${NC} 建立 .gitignore"

# 建立 context/ 世界模型資料夾
mkdir -p context

cat > context/ARCHITECTURE.md << 'EOF'
# Architecture

系統架構和資料流說明。

## 概述
<!-- 描述系統的主要組成部分 -->

## 資料流
<!-- 描述主要的資料流程 -->
```
[輸入] → [處理] → [輸出]
```

## 技術決策
<!-- 記錄重要的技術選擇和原因 -->

| 決策 | 選擇 | 原因 |
|------|------|------|
| | | |

## 平台差異
<!-- 如果有多平台，記錄差異 -->
EOF

cat > context/LEARNINGS.md << 'EOF'
# Learnings

記錄專案中學到的經驗，避免重複犯錯。
Claude 犯錯後，讓它更新這個文件。

---

## 格式範例

### 2025-XX-XX
#### 問題：[問題描述]
- 原因：為什麼會發生
- 修復：如何解決
- 規則：新增什麼規則到 CLAUDE.md
EOF

cat > context/DECISIONS.md << 'EOF'
# Architecture Decision Records (ADR)

記錄重要的設計決策，幫助未來理解「為什麼這樣做」。

---

## ADR-001: [決策標題]

**日期**: YYYY-MM-DD

**狀態**: [proposed | accepted | deprecated | superseded]

**背景**:
描述問題和限制條件。

**決策**:
我們決定...

**後果**:
- 優點：
- 缺點：
- 風險：
EOF

echo -e "${GREEN}✓${NC} 建立 context/ 世界模型"

# openspec init
if command -v openspec &> /dev/null; then
    openspec init -q 2>/dev/null || openspec init 2>/dev/null || echo "  (openspec init 需要手動確認)"
    echo -e "${GREEN}✓${NC} openspec init"
else
    echo -e "${YELLOW}⚠${NC} openspec 未安裝，跳過"
fi

# 安裝 repo-snapshot.sh 和 pre-commit hook
MAIN_BRAIN_DIR="$HOME/main-brain"
if [[ -f "$MAIN_BRAIN_DIR/scripts/repo-snapshot.sh" ]]; then
    mkdir -p scripts
    cp "$MAIN_BRAIN_DIR/scripts/repo-snapshot.sh" scripts/repo-snapshot.sh
    chmod +x scripts/repo-snapshot.sh
    echo -e "${GREEN}✓${NC} 安裝 repo-snapshot.sh"

    # Install pre-commit hook
    mkdir -p .git/hooks
    cat > .git/hooks/pre-commit << 'HOOKEOF'
#!/bin/bash
# pre-commit hook: auto-update repo snapshot in CLAUDE.md
SNAPSHOT_SCRIPT="scripts/repo-snapshot.sh"
if [[ -f "$SNAPSHOT_SCRIPT" ]]; then
    bash "$SNAPSHOT_SCRIPT" . 2>/dev/null
    git add CLAUDE.md 2>/dev/null
fi
HOOKEOF
    chmod +x .git/hooks/pre-commit
    echo -e "${GREEN}✓${NC} 安裝 pre-commit hook"

    # Run initial snapshot
    bash scripts/repo-snapshot.sh . 2>/dev/null
    echo -e "${GREEN}✓${NC} 生成初始 snapshot"
else
    echo -e "${YELLOW}⚠${NC} main-brain/scripts/repo-snapshot.sh 不存在，跳過 snapshot 設定"
fi

# 安裝 Cursor rules (from main-brain templates)
if [[ -d "$MAIN_BRAIN_DIR/templates" ]]; then
    mkdir -p .cursor/rules
    # Snapshot update rule
    if [[ -f "$MAIN_BRAIN_DIR/.cursor/rules/update-snapshot.mdc" ]]; then
        cp "$MAIN_BRAIN_DIR/.cursor/rules/update-snapshot.mdc" .cursor/rules/update-snapshot.mdc
    fi
    # Quality gate rule
    if [[ -f "$MAIN_BRAIN_DIR/templates/quality-gate.mdc.tmpl" ]]; then
        cp "$MAIN_BRAIN_DIR/templates/quality-gate.mdc.tmpl" .cursor/rules/quality-gate.mdc
    fi
    echo -e "${GREEN}✓${NC} 安裝 Cursor rules (snapshot + quality-gate)"
fi

# 安裝 Cursor commands (from main-brain templates)
if [[ -d "$MAIN_BRAIN_DIR/templates/commands" ]]; then
    mkdir -p .cursor/commands
    for tmpl in "$MAIN_BRAIN_DIR/templates/commands/"*.tmpl; do
        if [[ -f "$tmpl" ]]; then
            basename=$(basename "$tmpl" .tmpl)
            cp "$tmpl" ".cursor/commands/$basename"
        fi
    done
    echo -e "${GREEN}✓${NC} 安裝 Cursor commands (lesson)"
fi

# 初始 commit
git add -A
git commit -q -m "Initial commit: $PROJECT_NAME

$PROJECT_DESC"
echo -e "${GREEN}✓${NC} 初始 commit"

# ========== Phase 3: 環境配置 ==========

echo ""
echo -e "${BLUE}配置環境...${NC}"

# 產生 alias 名稱 (移除連字號)
ALIAS_NAME=$(echo "$PROJECT_NAME" | tr -d '-')

# 檢查 alias 是否已存在
if grep -q "alias $ALIAS_NAME=" ~/.zshrc 2>/dev/null; then
    echo -e "${YELLOW}⚠${NC} alias '$ALIAS_NAME' 已存在，跳過"
else
    echo "" >> ~/.zshrc
    echo "# $PROJECT_NAME" >> ~/.zshrc
    echo "alias $ALIAS_NAME=\"cd $FULL_PATH && cursor .\"" >> ~/.zshrc
    echo -e "${GREEN}✓${NC} 新增 alias: $ALIAS_NAME"
fi

# ========== ctb (Claude Telegram Bot) 設定 ==========

if command -v ctb &> /dev/null; then
    echo ""
    read -p "設定 Telegram Bot 遠端控制 (ctb)? [y/N]: " SETUP_CTB
    SETUP_CTB="${SETUP_CTB:-N}"
    if [[ "$SETUP_CTB" =~ ^[Yy]$ ]]; then
        CTB_ENV="$FULL_PATH/.env"
        GLOBAL_CTB_ENV="$HOME/.ctb.env"

        if [[ -f "$GLOBAL_CTB_ENV" ]]; then
            echo -e "  發現全域設定 $GLOBAL_CTB_ENV"
            read -p "  使用全域設定? [Y/n]: " USE_GLOBAL
            USE_GLOBAL="${USE_GLOBAL:-Y}"
            if [[ "$USE_GLOBAL" =~ ^[Yy]$ ]]; then
                cp "$GLOBAL_CTB_ENV" "$CTB_ENV"
                echo -e "${GREEN}✓${NC} 從全域設定複製 .env"
            fi
        fi

        # If .env still doesn't exist, prompt for tokens
        if [[ ! -f "$CTB_ENV" ]]; then
            echo "  需要 Telegram Bot 設定（從 @BotFather 取得）"
            read -p "  TELEGRAM_BOT_TOKEN: " TG_TOKEN
            read -p "  TELEGRAM_ALLOWED_USERS (逗號分隔 user IDs): " TG_USERS

            if [[ -n "$TG_TOKEN" && -n "$TG_USERS" ]]; then
                cat > "$CTB_ENV" << ENVEOF
TELEGRAM_BOT_TOKEN=$TG_TOKEN
TELEGRAM_ALLOWED_USERS=$TG_USERS
ENVEOF
                echo -e "${GREEN}✓${NC} 建立 .env (ctb 設定)"

                # Offer to save as global config
                if [[ ! -f "$GLOBAL_CTB_ENV" ]]; then
                    read -p "  儲存為全域設定 (~/.ctb.env)? [y/N]: " SAVE_GLOBAL
                    SAVE_GLOBAL="${SAVE_GLOBAL:-N}"
                    if [[ "$SAVE_GLOBAL" =~ ^[Yy]$ ]]; then
                        cp "$CTB_ENV" "$GLOBAL_CTB_ENV"
                        echo -e "${GREEN}✓${NC} 儲存全域設定"
                    fi
                fi
            else
                echo -e "${YELLOW}⚠${NC} Token 或 User ID 為空，跳過 ctb 設定"
            fi
        fi

        # Add bot alias
        BOT_ALIAS="${ALIAS_NAME}bot"
        if ! grep -q "alias $BOT_ALIAS=" ~/.zshrc 2>/dev/null; then
            echo "alias $BOT_ALIAS=\"cd $FULL_PATH && ctb\"" >> ~/.zshrc
            echo -e "${GREEN}✓${NC} 新增 alias: $BOT_ALIAS (啟動 Telegram bot)"
        fi
    fi
else
    echo -e "${YELLOW}⚠${NC} ctb 未安裝 (npm install -g ctb)，跳過 Telegram 設定"
fi

# source zshrc (在子 shell 中不會影響當前 shell)
echo -e "${YELLOW}!${NC} 請執行 'source ~/.zshrc' 或開新終端機以啟用 alias"

# ========== 完成 ==========

echo ""
echo -e "${GREEN}=== 專案建立完成 ===${NC}"
echo ""
echo "專案路徑: $FULL_PATH"
echo "快速開啟: $ALIAS_NAME"
if [[ -f "$FULL_PATH/.env" ]] && command -v ctb &> /dev/null; then
    BOT_ALIAS="${ALIAS_NAME}bot"
    echo "Telegram Bot: $BOT_ALIAS"
fi
echo ""
echo "下一步:"
echo "  1. source ~/.zshrc"
echo "  2. $ALIAS_NAME  (或 cursor $FULL_PATH)"
echo "  3. 在 Cursor 中輸入: plan: 規劃 $PROJECT_NAME 的架構"
if [[ -f "$FULL_PATH/.env" ]] && command -v ctb &> /dev/null; then
    echo "  4. $BOT_ALIAS  (啟動 Telegram 遠端控制)"
fi
echo ""

# 詢問是否開啟 Cursor
read -p "現在開啟 Cursor? [Y/n]: " OPEN_CURSOR
OPEN_CURSOR="${OPEN_CURSOR:-Y}"
if [[ "$OPEN_CURSOR" =~ ^[Yy]$ ]]; then
    # 優先用 cursor CLI，否則用 open
    if command -v cursor &> /dev/null; then
        cursor "$FULL_PATH"
    else
        open -a "Cursor" "$FULL_PATH"
    fi
fi
